(defvar rc/package-contents-refreshed nil)

(defun rc/package-refresh-contents-once ()
  (when (not rc/package-contents-refreshed)
    (setq rc/package-contents-refreshed t)
    (package-refresh-contents)))

(defun rc/require-one-package (package)
  (when (not (package-installed-p package))
    (rc/package-refresh-contents-once)
    (package-install package)))

(defun rc/require (&rest packages)
  (dolist (package packages)
    (rc/require-one-package package)))

(defun rc/require-theme (theme)
  (let* ((theme-name (symbol-name theme))
         (theme-package (intern (concat theme-name "-theme"))))
    (rc/require theme-package)
    (load-theme theme t)))

(defun rc/duplicate-line ()
  (interactive)
  (if (use-region-p)
      (let* ((start (region-beginning))
             (end   (region-end))
             (text  (buffer-substring-no-properties start end))
             insert-pos)
        (save-excursion
          (goto-char end)
          (setq insert-pos (point))
          (insert text))
        (goto-char insert-pos)
        (set-mark (point))
        (goto-char (+ insert-pos (length text)))
        (setq deactivate-mark nil)
        (setq mark-active t)
        (activate-mark))
    (let ((column (- (point) (point-at-bol)))
          (line (let ((s (thing-at-point 'line t)))
                  (if s (string-remove-suffix "\n" s) ""))))
      (move-end-of-line 1)
      (newline)
      (insert line)
      (move-beginning-of-line 1)
      (forward-char column))))
